// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdSI1uCbl3ih_QtzLTqHH_dw8gpkdxUg',
    appId: '1:807853167805:web:51833b423380a50137d3d4',
    messagingSenderId: '807853167805',
    projectId: 'flagrush-c280f',
    authDomain: 'flagrush-c280f.firebaseapp.com',
    storageBucket: 'flagrush-c280f.firebasestorage.app',
    measurementId: 'G-YM3BNELX8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1C4N0fcsjU6GXM16O7yeerYhuix6Nzs',
    appId: '1:807853167805:android:6bf2711454f434ce37d3d4',
    messagingSenderId: '807853167805',
    projectId: 'flagrush-c280f',
    storageBucket: 'flagrush-c280f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHV2irX64_9Fumathw7ztceOg20McUSA',
    appId: '1:807853167805:ios:5060798486daf14237d3d4',
    messagingSenderId: '807853167805',
    projectId: 'flagrush-c280f',
    storageBucket: 'flagrush-c280f.firebasestorage.app',
    iosBundleId: 'dev.sajo.flagrush',
  );
}
